// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgu_MdhmnqnyFXKUupxldq_3Flc1-0YlE',
    appId: '1:1028719079793:web:e9834508854dbf320106d0',
    messagingSenderId: '1028719079793',
    projectId: 'main-cedar-416307',
    authDomain: 'main-cedar-416307.firebaseapp.com',
    storageBucket: 'main-cedar-416307.appspot.com',
    measurementId: 'G-KLY9HMSW1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJy6a1A3R9k5G7DBJakh4GYAXXRShmt8E',
    appId: '1:1028719079793:android:9824a6c4013558090106d0',
    messagingSenderId: '1028719079793',
    projectId: 'main-cedar-416307',
    storageBucket: 'main-cedar-416307.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5VA15V2V0yH7tvHsS4aM5ncPhhyr99RA',
    appId: '1:1028719079793:ios:dadf896db52c6fb00106d0',
    messagingSenderId: '1028719079793',
    projectId: 'main-cedar-416307',
    storageBucket: 'main-cedar-416307.appspot.com',
    iosBundleId: 'com.example.googleSheetProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5VA15V2V0yH7tvHsS4aM5ncPhhyr99RA',
    appId: '1:1028719079793:ios:e74f7f1a81f3af590106d0',
    messagingSenderId: '1028719079793',
    projectId: 'main-cedar-416307',
    storageBucket: 'main-cedar-416307.appspot.com',
    iosBundleId: 'com.example.googleSheetProject.RunnerTests',
  );
}
